project:
  type: website

website:
  title: ""
  favicon: images/favicon.png
  google-analytics: "G-5L9T7K8KSS"

format:
  html:
    theme: 
      light: [cosmo, quarto-ext/bootstrap]
      dark: [cosmo, theme-dark.css]
    css: styles.css
    toc: false

editor: visual

execute:
  freeze: auto