project:
  type: website

website:
  title: ""

format:
  html:
    theme: 
      light: [cosmo, quarto-ext/bootstrap]
      dark: [cosmo, theme-dark.css]
    css: styles.css
    toc: false

editor: visual
